# Generated by Django 3.2 on 2022-04-09 17:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20220409_1623'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('query_set_with_price', django.db.models.manager.Manager()),
            ],
        ),
    ]
