# Generated by Django 4.0.3 on 2022-04-17 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_order_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта'),
            preserve_default=False,
        ),
    ]
