# Generated by Django 4.0.4 on 2022-05-19 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_productinorder_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена заполняется автоматически', max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта'),
        ),
    ]
