# Generated by Django 4.0.4 on 2022-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PR', 'Обработанный'), ('NP', 'Необработанный')], db_index=True, default='NP', max_length=2, verbose_name='Статус заказа'),
        ),
    ]
