# Generated by Django 4.0.4 on 2022-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='широта')),
                ('lon', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='долгота')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
            },
        ),
    ]
