version: "3.9"


services:
  db:
    image: "postgres:14.3-bullseye"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql # Создаёт БД и роль, если БД пуста

  frontend:
    command: bash -c 'parcel build bundles-src/index.js --dist-dir bundles --public-url="./"'

  nginx:
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
