version: "3.9"

volumes:
  frontend_data:
  media:


services:
  web:
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=false

  db:
    env_file:
      - .env
    restart: always

  frontend:
    restart: on-failure

  nginx:
    image: "depocoder/nginx_certbot:0.1"
    build:
      context: .
      dockerfile: ./etc/nginx/Dockerfile
    ports:
      - "443:443"