version: "3.9"

volumes:
  production_pg_data:

services:
  db:
    container_name: star_burger_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=star_burger
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    image: "postgres:14.3-bullseye"
    volumes:
      - production_pg_data:/var/lib/postgresql/data
