version: "3.9"

volumes:
  frontend_data:
  media:
  pg_data:
  letsencrypt_data:
  nginx_confs:

services:
  web:
    container_name: star_burger_web
    build:
        context: backend
    image: "star_burger_web:latest"
    network_mode: "host"
    command: "python -m gunicorn -b 0.0.0.0:8080 star_burger.wsgi:application"
    environment:
      - POSTGRES_HOST=db
      - STATIC_DIR_NAME=frontend
      - DEBUG=false
    volumes:
      - frontend_data:/code/frontend
      - media:/code/media
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    container_name: star_burger_db
    env_file:
      - .env
    restart: always
    image: "postgres:14.3-bullseye"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=star_burger

  frontend:
    container_name: star_burger_frontend
    restart: on-failure
    build:
      context: frontend
    image: star_burger_frontend:latest
    volumes:
      - frontend_data:/frontend
