version: "3.9"

volumes:
  frontend_data:
  pg_data:


services:
  web:
    container_name: star_burger_web
    build:
        context: backend
    command: python -m gunicorn -b 0.0.0.0:8080 star_burger.wsgi:application
    image: "star_burger_web:latest"
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - POSTGRES_HOST=db
      - STATIC_DIR_NAME=frontend
      - SECRET_KEY=DebugSecretKey
      - DEBUG=true
    volumes:
      - frontend_data:/code/frontend
      - ./media:/code/media
    depends_on:
      - db

  db:
    container_name: star_burger_db
    image: "postgres:14.3-bullseye"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=star_burger
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=P@ssw0rd

  frontend:
    container_name: star_burger_frontend
    build:
      context: frontend
    image: star_burger_frontend:latest
    volumes:
      - frontend_data:/static

