version: "3.9"

volumes:
  frontend_data:
  media:


services:
  web:
    restart: always

  db:
    restart: always

  frontend:
    restart: on-failure

  nginx:
    image: "depocoder/nginx_certbot:0.1"
    build:
      context: .
      dockerfile: ./etc/nginx/Dockerfile
    volumes:
      - frontend_data:/frontend
      - media:/media
    ports:
      - "80:80"
      - "443:443"