version: "3.9"

volumes:
  letsencrypt_data:
  nginx_confs:



services:
  web:
    restart: always
    env_file:
      - .env
    environment:
      - DEBUG=false

  db:
    env_file:
      - .env
    restart: always

  frontend:
    restart: on-failure

  nginx:
    image: "depocoder/nginx_certbot:0.1"
    build:
      context: .
      dockerfile: ./etc/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - letsencrypt_data:/etc/letsencrypt/
      - nginx_confs:/etc/nginx/sites-available
