version: "3.9"

volumes:
  production_pg_data:

services:
  web:
    container_name: star_burger_web
    build:
        context: backend
    image: "star_burger_web:latest"
    command: "python -m gunicorn -b 0.0.0.0:8080 star_burger.wsgi:application"
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - POSTGRES_HOST=db
      - DEBUG=false
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - SECRET_KEY=${SECRET_KEY:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
    volumes:
      - ./media:/code/media
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    container_name: star_burger_db
    env_file:
      - .env
    restart: always
    image: "postgres:14.3-bullseye"
    volumes:
      - production_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=star_burger
