version: "3.9"


services:
  web:
    command: bash -c 'python manage.py collectstatic --no-input &&
      python -m gunicorn -b 0.0.0.0:8080 star_burger.wsgi:application'
    environment:
      - SECRET_KEY=DebugSecretKey
        DEBUG=true

  db:
    image: "postgres:14.3-bullseye"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=some_user
      - POSTGRES_PASSWORD=P@ssw0rd

  nginx:
      volumes:
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
