# Generated by Django 4.0.3 on 2022-04-17 10:05

from django.db import migrations


def copy_price_to_product_in_order(apps, schema_editor):
    ProductInOrder = apps.get_model('foodcartapp', 'ProductInOrder')
    Product = apps.get_model('foodcartapp', 'Product')
    for product in Product.objects.all():
        ProductInOrder.objects.filter(product_id=product.pk).update(price=product.price)


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0042_productinorder_price'),
    ]

    operations = [
        migrations.RunPython(copy_price_to_product_in_order),
    ]
