# Generated by Django 4.0.3 on 2022-04-17 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220417_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта'),
        ),
    ]
