# Generated by Django 4.0.4 on 2022-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_alter_order_managers_alter_productinorder_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('PR', 'Обработанный'), ('NP', 'Необработанный')], db_index=True, default='NP', max_length=2),
        ),
    ]
