# Generated by Django 4.0.4 on 2022-05-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('CS', 'Наличные'), ('EC', 'Электронный'), ('NC', 'Не выбрано')], db_index=True, default='NC', max_length=2, verbose_name='Способ оплаты'),
        ),
    ]
