# Generated by Django 4.0.4 on 2022-05-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_pay_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='who_cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_who_cook', to='foodcartapp.restaurant', verbose_name='Кто готовит?'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_products', to='foodcartapp.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_restaurants', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
