# Generated by Django 4.0.4 on 2022-05-25 14:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_who_cook_alter_restaurantmenuitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена заполняется автоматически', max_digits=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена продукта'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
