# Generated by Django 4.0.4 on 2022-05-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_phonenumber_alter_productinorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='who_cook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_which_cook', to='foodcartapp.restaurant', verbose_name='Кто готовит?'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_carts', to='foodcartapp.product', verbose_name='Продукт'),
        ),
    ]
