# Generated by Django 4.0.4 on 2022-05-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_who_cook_alter_productinorder_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=100, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='contact_phone',
            field=models.CharField(max_length=50, verbose_name='контактный телефон'),
        ),
    ]
